# Generated by Django 5.2.1 on 2025-05-17 06:59

import user.usermanager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.usermanager.UserManager()),
            ],
        ),
    ]
