# Generated by Django 5.2.1 on 2025-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField(null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('answer_text', models.TextField(null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answers/')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
